apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deploy
  labels:
    name: worker-app-deploy
    app: worker-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: worker-app-pod
      app: worker-app
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app-pod
        app: worker-app
    spec:
      containers:
        - name: worker-app
          image: kodekloud/examplevotingapp_worker:v1